version: "3.7"

services:
    timescale-primary:
        image: "timescale/timescaledb:latest-pg12"
        container_name: "timescale-primary"
        environment: 
            - "POSTGRES_USER=postgres"
            - "POSTGRES_PASSWORD=postgres"
            - "PGDATA=/var/lib/postgresql/data"
            - "REPLICA_POSTGRES_USER=repuser"
            - "REPLICA_POSTGRES_PASSWORD=repuser"
            - "REPLICATE_TO=timescale-replica"
            - "REPLICA_NAME=r1"
            - "SYNCHRONOUS_COMMIT=off"
        environment:
            REPLICATION_SUBNET: "10.0.0.0/24"
        ports:
            - "5432:5432"
        volumes:
            - "./replication.sh:/docker-entrypoint-initdb.d/replication.sh"
            - "./data/primary:/var/lib/postgresql/data"
        networks: 
            - "timescale-net"            

    timescale-replica:
        image: "timescale/timescaledb:latest-pg12"
        container_name: "timescale-replica"
        environment: 
            - "POSTGRES_USER=repuser"
            - "POSTGRES_PASSWORD=repuser"
            - "PGDATA=/var/lib/postgresql/data"
            - "REPLICA_NAME=r1"
            - "REPLICATE_FROM=timescale-primary"       
        ports:
            - "5433:5432"
        volumes:
            - "./data/replica:/var/lib/postgresql/data"
        networks: 
            - "timescale-net"

networks:
    timescale-net:
        external: false
        name: "timescale-net"
